AllCops:
  Include:
    - 'lib/**/*.rb'
    - 'lib/**/*.rake'
    - 'spec/**/*.rb'
    - 'Gemfile'
    - 'Rakefile'
  Exclude:
    - 'bin/**/*'
    - 'spec/dummy/**/*'
    - 'tmp/**/*'
    - 'gemfiles/vendor/**/*'
    - 'vendor/**/*'
  DisplayCopNames: true
  StyleGuideCopsOnly: false
  TargetRubyVersion: 2.2

Style/Documentation:
  Exclude:
    - 'spec/**/*.rb'

Style/StringLiterals: 
  Enabled: false

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*.rb'

Metrics/MethodLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/LineLength:
  Max: 100

Bundler/OrderedGems:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false
