AllCops:
  Include:
    - 'lib/**/*.rb'
    - 'lib/**/*.rake'
    - 'spec/**/*.rb'
    - 'Gemfile'
    - 'Rakefile'
  Exclude:
    - 'bin/**/*'
    - 'spec/dummy/**/*'
  DisplayCopNames: true
  StyleGuideCopsOnly: false
  TargetRubyVersion: 2.3

Style/Documentation:
  Exclude:
    - 'spec/**/*.rb'

Style/StringLiterals: 
  Enabled: false

Layout/BlockDelimiters:
  Exclude:
    - 'spec/**/*.rb'

Metrics/MethodLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/LineLength:
  Max: 100
