AllCops:
  # Include gemspec and Rakefile
  Include:
    - 'lib/**/*.rb'
    - 'lib/**/*.rake'
    - 'spec/**/*.rb'
  Exclude:
    - 'bin/**/*'
    - 'spec/dummy/**/*'
  RunRailsCops: true
  DisplayCopNames: true
  StyleGuideCopsOnly: false

Style/Documentation:
  Exclude:
    - 'spec/**/*.rb'

Style/StringLiterals: 
  Enabled: false

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*.rb'

Metrics/MethodLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/LineLength:
  Max: 100

Rails/Date:
  Enabled: false

Rails/TimeZone:
  Enabled: false