language: ruby
cache: bundler

notifications:
  email: false

before_install:
  - gem install bundler
  - gem update bundler

matrix:
  include:
    - rvm: 2.3.1
      gemfile: gemfiles/rails42.gemfile

    - rvm: 2.4.0
      gemfile: gemfiles/rails5.gemfile
