language: ruby
cache: bundler

dist: trusty
sudo: false

notifications:
  email: false

before_install:
  - gem install bundler
  - gem update bundler

matrix:
  include:
    - rvm: ruby-head
      gemfile: gemfiles/railsmaster.gemfile
    - rvm: 2.4.1
      gemfile: gemfiles/rails5.gemfile
    - rvm: 2.3.1
      gemfile: gemfiles/rails42.gemfile
  allow_failures:
    - rvm: ruby-head
      gemfile: gemfiles/railsmaster.gemfile
